# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 526d683dcf4146fb345571f84b99a0ce2f03a85ca0da54a64cb75ead3fff8e5fb1a656171e330e3d716b95971ce9746327ae6555f53ab0972239ff16fd949460

test:
  secret_key_base: ba2ab787e20bd6fe910632481b6633a1e7d7789b7bcf5eb917965448945ec2f298d4f489e1ced0f91a8310359959c136115b4d9d8812eeee3c1e2e8318161558

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
